name: yuki-no-kit

on:
  schedule:
    - cron: "0 0 */16 * *" # Every 16 days
  workflow_dispatch:

jobs:
  yuki-no:
    runs-on: ubuntu-latest
    steps:
      - uses: Gumball12/yuki-no@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

          head-repo: https://github.com/sveltejs/kit
          labels: kit

          track-from: f430a68937744212d2b1bd0ee920cc89cc6f696f

          include: |
            documentation/docs/**

          release-tracking: false
