name: yuki-no

on:
  schedule:
    - cron: "0 0 */14 * *" # Every 14 days
  workflow_dispatch:

jobs:
  yuki-no:
    runs-on: ubuntu-latest
    steps:
      - uses: Gumball12/yuki-no@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

          head-repo: https://github.com/sveltejs/svelte

          track-from: 94bd27953e0a5ffef80e9451b27e122d185d093f

          include: |
            documentation/docs/**

          release-tracking: false
